backend:
  name: github
  repo: tommy351/zespia.tw

publish_mode: editorial_workflow

media_folder: source/images/uploads
public_folder: /images/uploads

collections:
  - name: post
    label: Post
    folder: source/_posts
    create: true
    slug: "{{fields.slug}}"
    fields:
      - label: Layout
        name: layout
        widget: string
        default: post
      - label: Title
        name: title
        widget: string
      - label: Slug
        name: slug
        widget: string
        hint: "Format: YYYY-MM-DD-slug"
        pattern:
          ['\d{4}-\d{2}-\d{2}-.+', 'The format must be "YYYY-MM-DD-slug"']
      - label: Tags
        name: tags
        widget: list
        required: false
      - label: Body
        name: body
        widget: markdown
